var structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader =
[
    [ "ComputeShader", "structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader_1_1ComputeShader.html", "structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader_1_1ComputeShader" ],
    [ "GlobalCountersIntoLightIndexList", "structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader_1_1GlobalCountersIntoLightIndexList.html", "structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader_1_1GlobalCountersIntoLightIndexList" ],
    [ "ShaderResources", "structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader_1_1ShaderResources.html", "structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader_1_1ShaderResources" ],
    [ "ThreadGroupCount", "structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader_1_1ThreadGroupCount.html", "structne_1_1LightingShaderResourceManager_1_1ComputeShaderData_1_1LightCullingComputeShader_1_1ThreadGroupCount" ]
];